package com.freelancer.videoeditor.config;

import android.os.Environment;

import java.util.ArrayList;
import java.util.List;

public class AppConst {
    public static final int ACTION_SAVE = 0;
    public static final int ALPHA_FILTER = 40;
    public static final String ASSETS = "file:///android_asset";
    public static final String ASSETS_EMOTICON = "file:///android_asset/sticker/emo/";
    public static final String ASSETS_PATH_FOLDER_BACKGROUND = "file:///android_asset/background";
    public static final String ASSETS_PATH_FOLDER_BORDER = "file:///android_asset/border";
    public static final String ASSETS_PATH_FOLDER_FILTER = "file:///android_asset/filter";
    public static final String ASSETS_TICKET = "file:///android_asset/sticker/";
    public static final String ASSET_FOLDER_EMO_NAME = "sticker/emo";
    public static final String ASSET_FOLDER_FILTER_NAME = "filter";
    public static final String BUNDLE_KEY_IS_SORT_TAB = "IS_SORT_TAB";
    public static final int EMOTICON_MAX_COLUMNS = 8;
    public static final int EMOTICON_MAX_ROWS = 2;
    public static final String FOLDER_APP = "/Frames/VideoMaker/";
    public static final String FOLDER_BACKGROUND = "/Background/";
    public static final String FOLDER_FILTER = "/Filter/";
    public static final String FORMAT_BACKGROUND = ".jpg";
    public static final String FORMAT_FILLTER = ".jpg";
    public static final String FORMAT_FRAME = ".png";
    public static final int HEIGHT_FRAME = 800;
    public static final String KEY_ADMOB_BANNER = "KEY_ADMOB_BANNER";
    public static final String KEY_ADMOB_FULL_BANNER = "KEY_ADMOB_FULL_BANNER";
    public static final String LINK_ROOT = "http://139.59.241.64/App";
    public static final String NAME_PHOTO_SHARE = "share.png";
    public static String PATH_FILE_SAVE_PHOTO = "mnt/sdcard/Pictures_VideoMaker/";
    public static String PATH_FILE_SAVE_SHARE_PHOTO = "mnt/sdcard/Share/";
    public static final String PREFIX_BACKGROUND = "background";
    public static final String PREFIX_BORDER = "border";
    public static final String PREFIX_FILTER = "filter";
    public static final String PREFIX_THUMB_BACKGROUND = "background";
    public static final String PREFIX_THUMB_FRAME = "frame";
    public static final int REQUEST_CODE_CHOOSE_PHOTO_VIA_CAMERA = 0;
    public static final int REQUEST_CODE_CHOOSE_PHOTO_VIA_FILE = 1;
    public static final int REQUEST_CODE_STICKER_SCREEN = 109;
    public static String[] STICKER_COLOR_DEFAULT = null;
    public static final int TYPE_PHOTO = 1;
    public static final int TYPE_STICKER = 2;
    public static final int TYPE_TEXT = 3;
    public static final int WIDTH_FRAME = 800;
    public static final float ZOOM_MAX = 5.0f;
    public static final float ZOOM_MIN = 0.1f;
    public static final int WIDTH_VIDEO = 720;
    public static final String OUT_VIDEO_NAME_FORMAT = "yyyy_MM_dd_hh_mm_ss_a";

    public static final String ACTION_INTENT_FILTER_PHOTO_CROP = "com.BestPhotoEditor.CropPhoto.COMPLETED";
    public static final String APP_ID = "ca-app-pub-5692934122522554~5955826829";
    public static final String ASSET_FILTER_NAME = "filter_video";
    public static final String ASSET_FOLDER_BORDER_NAME = "overlay_border";
    public static final String ASSET_FOLDER_EFFECT_NAME = "effect";
    public static final String ASSET_FOLDER_EFFECT_VIDEO_NAME = "effect/video";
    public static final String ASSET_PREFIX_FILTER_NAME = "filter";
    public static final String AUDIO_COPY_TEMP = ".TempAudioCopy";
    public static final String AUDIO_LOOP_TEMP = ".AudioLoop";
    public static final String BASE_GOOGLE_PLAY = "https://play.google.com/store/apps/details?id=";
    public static final String BEAUTY_MAKEUP = "com.BestPhotoEditor.CatFace.PhotoEditor";
    public static final String BUNDLE_KEY_HOME = "BACK_HOME";
    public static final String BUNDLE_KEY_LIST_IMG_PICK = "LIST_IMG_PICK";
    public static final String BUNDLE_KEY_VIDEO_OPEN_FROM_MY_VIDEO = "VIDEO_OPEN_FROM_MY_VIDEO";
    public static final String BUNDLE_KEY_VIDEO_URL = "VIDEO_URL";
    public static final int CURRENT_CROP_VERSION = 2;
    public static final int DEFAULT_DURATION_SELECT_INDEX = 3;
    public static final String DEFAULT_INTERVAL_IMAGE = "2";
    public static final float DEFAULT_OPACITY = 1.0f;
    public static final boolean DEV_MODE = false;
    public static final String DOT = ".";
    public static final int EFFECT_DEFAULT_DURATION = 14;
    public static final String EFFECT_DEFAULT_NAME = "effect0.mp4";
    public static final String EFFECT_LOOP_TEMP = ".EffectLoop";
    public static final String EFFECT_NONE_NAME = "NONE";
    public static final String FILTER_TEMP_NAME = "Filter.png";
    public static final String FOLDER_THEME = "overlay_border";
    public static final String FORMAT_DATE_DEFAULT = "yyyy/MM/dd";
    public static final String FORMAT_DATE_VN = "dd/MM/yyyy";
    public static final String FORMAT_FILTER = ".png";
    public static final String FORMAT_OUT_IMAGE = ".jpg";
    public static final String FULL_ASSET_EFFECT0_THUMB = "file:///android_asset/effect/thumb/thumb0.png";
    public static final String FULL_ASSET_EFFECT0_VIDEO = "file:///android_asset/effect/video/effect0.mp4";
    public static final String FULL_ASSET_FOLDER_BORDER_NAME = "file:///android_asset/overlay_border";
    public static final String FULL_ASSET_FOLDER_EFFECT_FOLDER = "file:///android_asset/effect";
    public static final String FULL_ASSET_FOLDER_FILTER_NAME = "file:///android_asset/filter_video";
    public static int HEIGHT_IMAGE = WIDTH_VIDEO;
    public static final int HEIGHT_VIDEO = 720;
    public static final int HOUR_EVERY_CHECK_OPEN_APP_INTERVAL = 24;
    public static final int IGNORE_PERCENT_LOOP = 5;
    public static final int INDEX_ADS_LIST_APP_MENU_LEFT = 2;
    public static final List<String> LIST_PERMISSION_REQUEST = new ArrayList<>();
    public static final int MAX_SIZE_SELECT_PHOTO = 60;
    public static final String MEDIA_TEXT_TEMP = "MY_LIST.txt";
    public static final int MIN_SIZE_SELECT_PHOTO = 3;
    public static final String MP3_ZING_FOLDER = "ZingMp3";
    public static final String MP3_ZING_FOLDER1 = "Zing MP3";
    public static final String NAME_STORE = "Best+Photo+Editor";
    public static final String NAME_STORE_GAME = "BAZOOKA";
    public static final String NO_MEDIA_NAME = ".nomedia";
    public static final int NUMBER_START_IMAGE = 1;
    public static final String OUR_NO_MEDIA = "mnt/sdcard/FreeVideoEditor/Temp/.nomedia";
    public static final String OUT_AUDIO_TEMP = ".AudioCopyTemp";
    public static final String RELATIVE_TEMP_FOLDER = (Environment.getExternalStorageDirectory().getAbsolutePath() + "/FreeVideoEditor/Temp/");
    public static final String OUT_AUDIO_TEMP_FOLDER = (RELATIVE_TEMP_FOLDER + "Audio");
    public static final String OUT_BORDER_TEMP_FOLDER = "mnt/sdcard/FreeVideoEditor/Temp/Border";
    public static final String OUT_EFFECT_TEMP_FOLDER = (RELATIVE_TEMP_FOLDER + "Effect");
    public static final String OUT_FILTER_TEMP_FOLDER = "mnt/sdcard/FreeVideoEditor/Temp/Filter";
    public static final String OUT_IMAGE_TEMP_FOLDER = "mnt/sdcard/FreeVideoEditor/Temp/Image";
    public static final String OUT_LOOP_MEDIA_TEMP_FOLDER = "mnt/sdcard/FreeVideoEditor/Temp/Loop";
    public static final String OUT_VIDEO_FOLDER = "mnt/sdcard/FreeVideoEditor/FreeVideoEditor";
    public static final String OUT_VIDEO_PREFIX = "Video_";
    public static final String OUT_VIDEO_TEMP_FOLDER = "mnt/sdcard/FreeVideoEditor/Temp/Video";
    public static final String PACKAGE_NAME_CROP = "com.BestPhotoEditor.CropPhoto";
    public static final String PREFIX_OUT_IMAGE = ".Image";
    public static final int PUSH_NO_LONGER_USER_DAY = 3;
    public static final String ROOT_FOLDER = "mnt/sdcard/FreeVideoEditor/";
    public static final String SERVER_ENDPOINT = "http://139.59.241.64/";
    public static final String SHARE_PREFS_JSON_EFFECT = "JSON_EFFECT";
    public static final String SHARE_PREFS_LAST_OPEN_APP = "LAST_OPEN_APP";
    public static final String SHARE_PREFS_MORE_APP = "MORE_APP";
    public static final String TEMP_FOLDER = "mnt/sdcard/FreeVideoEditor/Temp/";
    public static final int TOOLBOX_COLUMNS_BORDER_COUNT = 6;
    public static final int TOOLBOX_COLUMNS_EFFECT_COUNT = 6;
    public static final int TOOLBOX_COLUMNS_FILTER_COUNT = 6;
    public static final String URL_STICKER = "App/PhotoEditor/Stickers/FreeVideoEditor_BESTPHOTOEDITOR_Stickers.php";
    public static final String VIDEO_TEMP_NAME = ".VideoTemp";
    public static final String VIDEO_WITH_AUDIO_TEMP_NAME = ".VideoTempAudio";
    public static final String VIDEO_WITH_BORDER_TEMP = ".VideoBorderTemp";
    public static final String VIDEO_WITH_EFFECT_TEMP = ".VideoEffectTemp";
    public static final String VIDEO_WITH_FILTER_TEMP = ".VideoFilterTemp";
    public static int WIDTH_IMAGE = WIDTH_VIDEO;

    static {
        String[] strArr = new String[TYPE_STICKER];
        strArr[REQUEST_CODE_CHOOSE_PHOTO_VIA_CAMERA] = "#f5f5f5";
        strArr[TYPE_PHOTO] = "#e7e7e7";
        STICKER_COLOR_DEFAULT = strArr;
    }

    public static ArrayList<String> FORMAT_IMAGE = new ArrayList<String>() {
        {
            add(".PNG");
            add(".JPEG");
            add(AppConst.FORMAT_FILLTER);
            add(AppConst.FORMAT_FRAME);
            add(".jpeg");
            add(".JPG");
            add(".GIF");
            add(".gif");
        }
    };
}
